# Generated by Django 2.1.5 on 2019-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('menu', models.CharField(max_length=50)),
            ],
        ),
    ]
