# Generated by Django 2.1.5 on 2019-01-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20190130_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='menu',
        ),
    ]
