# Generated by Django 2.1.5 on 2019-01-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_basket_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_app.Menu'),
            preserve_default=False,
        ),
    ]
