# Generated by Django 2.1.5 on 2019-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_basket_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
