# Generated by Django 2.1.5 on 2019-02-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_remove_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
