# Generated by Django 2.1.5 on 2019-01-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20190126_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
